name: Bxb的文档笔记

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码到打包环境中
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 安装PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: 安装依赖
        run: pnpm install
      - name: 打包
        run: pnpm build
      - name: 检查产物路径
        run: ls -R docs/.vitepress/dist
      - name: 上传项目
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          name: docs
          path: docs/.vitepress/dist
          retention-days: 3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
