name: Bxb的文档笔记

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码到打包环境中
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Node 和 Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'  # 使用 Yarn 缓存

      - name: 安装依赖
        run: yarn install --frozen-lockfile  # 使用 lockfile 安装依赖

      - name: 打包
        run: yarn build  # 使用 Yarn 进行构建

      - name: 上传项目
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
