name: Bxb的文档笔记

on:
  push:
    branches:
      - main  # 你希望触发自动部署的分支, 这里是 main
  pull_request:
    branches:
      - main  # 可选，如果你也希望在提交 PR 时触发构建

jobs:
  # 打包流程
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码到打包环境中
        uses: actions/checkout@v4
        with:
          # 获取全部提交记录，如果未启用lastUpdated，则不需要
          fetch-depth: 0
      - name: 安装Yarn
        uses: borales/actions-yarn@v3
        with:
          version: '1.22.19'  # 或者指定其他版本的 Yarn
      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: 启用Github Pages并读取文档元数据
        uses: actions/configure-pages@v4
      - name: 安装依赖
        run: yarn install  # 使用 yarn 代替 pnpm
      - name: 打包
        run: yarn build  # 使用 yarn build 代替 pnpm build
      - name: 上传项目
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署流程
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
