name: Bxb的文档笔记

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码到打包环境中
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn  # 改为 yarn 的缓存

      - name: 启用Github Pages并读取文档元数据
        uses: actions/configure-pages@v4

      - name: 安装依赖
        run: yarn install  # 改为 yarn 安装

      - name: 打包
        run: yarn build  # 改为 yarn 构建

      - name: 上传项目
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
